Repository brettcannon/mousebender, pull requests merged in 2020-05, with the labels that each got.

#22 Support most in-service Python versions.
  .github/workflows/main.yml
  mousebender/simple.py
  pyproject.toml
  tests/test_simple.py
Labels: impact-breaking

#26 Single letter typo fix.
  README.rst
Labels: impact-project

#25 Add support for PEP 592: yanked & provide default values
  mousebender/simple.py
  tests/test_simple.py
Labels: enhancement, impact-feature

#29 Turn back on release-often
  .flake8
  .github/workflows/ci.yml
  .github/workflows/release.yml
  pyproject.toml
Labels: impact-project
